### ISSUE TITLE
Gojek web page is returning 404

### ISSUE THREAD

**Issue by ramitsurana** [gojek/turing#51]
Hi,

I wanted to explore some docs for turing, and happen to discover the https://www.gojek.io/turing. But it seems to return 404.

**Comment by romanwozniak** [comment]
Hi @ramitsurana, I don't think that we ever used [https://www.gojek.io/turing](https://www.gojek.io/turing) URL. 
We will try to setup user docs and tutorials in the near future, but in the meantime, you can explore [architecture docs](https://github.com/gojek/turing#architecture-overview) and [REST API](https://github.com/gojek/turing/blob/main/api/swagger.yaml)

P.S. you can check a blog post about Turing as well: https://www.gojek.io/blog/finding-intelligence-with-turing

**Comment by ramitsurana** [comment]
Thanks, @romanwozniak for sharing the blog and other references. Are we also releasing go packages for turing in binary format?

**Comment by romanwozniak** [comment]
@ramitsurana we do not plan to publish any binaries, because the build artifacts aren't platform-agnostic. You can build binaries on your own using Make targets, or even better, build a Docker image and use it with docker-compose as described in [README.md](https://github.com/gojek/turing#getting-started). We also plan to publish pre-built docker images to ghcr.io, but I can't provide you with an exact timeline on when it will happen

**Comment by ramitsurana** [comment]
Okay. Thanks @romanwozniak

**Comment by romanwozniak** [comment]
@ramitsurana a quick update, we have started publishing all artifacts for our releases (you can find them here:[/gojek/packages](https://github.com/orgs/gojek/packages?repo_name=turing)) and we also updated our deployment charts to make it possible to install Turing with helm (see: [README](https://github.com/gojek/turing/tree/main/infra/charts/turing)).

Closing this issue for now.
